### PR TITLE
Upgrade to Robolectric 3.0

### PR DESCRIPTION
**Pull request by taig**
3.0-SNAPSHOT can no longer be resolved

### CODE REVIEW

**Comment by nightscape** [comment]
:+1:

**Comment by nightscape** [comment]
Hi @zbsz, is there anything blocking this PR? I'm running Robotest with Robolectric 3.0 in my project, haven't found any problems so far :)

**Comment by zbsz** [comment]
Hi, sorry for delay, missed notifications somehow. 
Snapshot is still working for me, probably because I have it deployed locally :)
Thanks for update, merging it now.

**Comment by taig** [comment]
Could you push a new release, please? :3

**Comment by zbsz** [comment]
good idea, done

**Comment by zbsz** [comment]
robotest 0.12 is now available from maven central, no need to use ugly github resolver anymore

**Comment by nightscape** [comment]
:thumbsup:

**Pull request merged**
